apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: unifi-unifi-transport@kubernetescrd
spec:
  selector:
    app.kubernetes.io/name: unifi
  type: LoadBalancer
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      appProtocol: https
      protocol: TCP
    - name: device-comm
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: secure-redirect
      port: 8843
      targetPort: 8843
      protocol: TCP
    - name: http-redirect
      port: 8880
      targetPort: 8880
      protocol: TCP
    - name: speedtest
      port: 6789
      targetPort: 6789
      protocol: TCP